name: Run GPU Scraper

on:
  schedule:
    - cron: '0 15 * * *'   # 
  workflow_dispatch:       # lets you run manually from GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AWS script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        run: python AWS_script.py

      - name: Run Verda script
        run: python Verda_script.py

      - name: Run Coreweave script
        run: python coreweave.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add verda_pricing_history.csv
          git commit -m "Update GPU pricing data - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
